services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./work:/work
    ports:
      - "8000:8000"
    environment:
      - WORKSPACE_DIR=/work
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    command: uvicorn src.web.backend.api:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - plm-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./src/web/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - plm-network
  vscode:
    build:
      context: .
      dockerfile: Dockerfile.vscode
    ports:
      - "8080:8080"
    volumes:
      - ./work:/work
    environment:
      - WORKSPACE=/work
    depends_on:
      - backend
networks:
  plm-network:
    driver: bridge 