version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./work:/work
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WORKSPACE_DIR=/work

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

  vscode:
    build:
      context: .
      dockerfile: Dockerfile.vscode
    ports:
      - "8080:8080"
    volumes:
      - ./work:/work
    environment:
      - WORKSPACE=/work
    depends_on:
      - backend

volumes:
  work: 