# PLM Settings Configuration
# Folder paths relative to workspace
source_folder: src  # Used for both input (code analysis) and output (generated code)
requirements_folder: requirements
architecture_folder: architecture

# Folder structure preference (hierarchical or flat)
folder_structure: hierarchical

# Preferred programming languages for code generation
preferred_languages:
  - python
  - javascript

# Custom instructions for LLM interactions
custom_llm_instructions: 

# Source code scanning patterns
source_include_patterns:
  - **/*.py
  - **/*.js
  - **/*.ts

# Patterns to exclude from source scanning
source_exclude_patterns:
  - **/node_modules/**
  - **/__pycache__/**
  - **/venv/**

# Domain configurations
domains:
  ui:
    name: User Interface
    description: User interface components and interactions

  motor_and_doors:
    name: Motor and Doors
    description: Motor control and door management systems

  offboard:
    name: Offboard Systems
    description: External and cloud-based systems

