architecture_folder: architecture
custom_llm_instructions: ''
domains:
  fmi_interface:
    description: Implements the Functional Mock-up Interface (FMI) standard for managing
      co-simulation models.
    name: FMI Interface
    subdomain_ids:
    - component_management
  quic_client:
    description: Facilitates communication and simulation execution using a Functional
      Mock-up Unit (FMU) over a QUIC network connection.
    name: QUIC Client
    subdomain_ids:
    - fmu_management
    - simulation_execution
    - message_handling
  quic_network:
    description: Manages the underlying QUIC connection and stream handling for both
      client and server functionalities.
    name: QUIC Network
    subdomain_ids:
    - connection_management
    - stream_management
  quic_server:
    description: Handles client connections and facilitates communication for simulation
      environments using the QUIC protocol.
    name: QUIC Server
    subdomain_ids:
    - configuration_management
    - connection_management
    - message_handling
    - simulation_management
  shared_memory:
    description: Defines and manages shared memory structures for inter-process communication.
    name: Shared Memory
    subdomain_ids:
    - memory_management
folder_structure: hierarchical
preferred_languages:
- python
- javascript
- cpp
requirements_folder: requirements
source_exclude_patterns:
- '**/node_modules/**'
- '**/__pycache__/**'
- '**/venv/**'
- '**/build/**'
- '**/dist/**'
source_folder: src
source_include_patterns:
- '**/*.py'
- '**/*.js'
- '**/*.ts'
- '**/*.cpp'
- '**/*.hpp'
- '**/*.h'
